# Generated by Django 4.2.25 on 2025-12-17 08:31

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Brief title for your testimonial', max_length=200, validators=[django.core.validators.MinLengthValidator(10)])),
                ('content', models.TextField(help_text='Share your experience (50-1000 characters)', validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(1000)])),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rate your overall experience')),
                ('display_name', models.CharField(blank=True, help_text="Name to display publicly (leave blank to use 'Anonymous')", max_length=100)),
                ('location', models.CharField(blank=True, help_text='Your city/location (optional)', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes for admin use')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this testimonial prominently')),
                ('display_order', models.IntegerField(default=0, help_text='Order for displaying testimonials (higher numbers first)')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_testimonials', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testimonials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-display_order', '-created_at'],
                'indexes': [models.Index(fields=['status', 'is_featured'], name='testimonial_status_26d084_idx'), models.Index(fields=['rating', 'created_at'], name='testimonial_rating_de5606_idx')],
            },
        ),
    ]
