# Generated by Django 4.2.25 on 2025-12-02 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_appointment'),
        ('payments', '0002_remove_payment_updated_at_alter_payment_reference_and_more'),
    ]

    operations = [
    ]
