# Generated by Django 4.2.25 on 2025-12-15 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_doctorprofile_applied_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('amharic', 'Amharic'), ('afan_oromo', 'Afan Oromo'), ('tigrigna', 'Tigrigna'), ('somali', 'Somali')], default='en', max_length=20),
        ),
    ]
